---

- name: Nginx - Copy site config
  become: true
  ansible.builtin.template:
    src: default.conf.j2
    dest: "{{ config_path }}"
    mode: '0755'
  notify: Start nginx service
  tags: lighthouse

- name: Nginx - Flush handlers
  ansible.builtin.meta: flush_handlers
  tags: lighthouse
