---

- name: Yum - Add Nginx Repo
  become: true
  ansible.builtin.copy:
    dest: "/etc/yum.repos.d/nginx-stable.repo"
    content: |
      [nginx-stable]
      name=nginx stable repo
      baseurl=http://nginx.org/packages/centos/$releasever/$basearch/
      gpgcheck=1
      enabled=1
      gpgkey=https://nginx.org/keys/nginx_signing.key
      module_hotfixes=true
  tags: lighthouse

- name: Yum - Install packages
  become: true
  ansible.builtin.yum:
    name:
      - git
      - nginx
    state: latest
  tags: lighthouse
